index:
    path: /
    controller: App\Controller\ProstagesController::index

detailsEntreprise:
    path: /detailsEntreprise/{nomEntreprise}
    controller: App\Controller\ProstagesController::detailsEntreprise

detailsFormation:
    path: /detailsFormation/{nomFormation}
    controller: App\Controller\ProstagesController::detailsFormation

detailsStage:
    path: /detailsStage/{idStage}
    controller: App\Controller\ProstagesController::detailsStage

ajouterEntreprise:
    path: /ajouterEntreprise
    controller: App\Controller\ProstagesController::ajouterEntreprise

modifierEntreprise:
    path: /modifierEntreprise/{nom}
    controller: App\Controller\ProstagesController::modifierEntreprise

ajouterStage:
    path: /ajouterStage
    controller: App\Controller\ProstagesController::ajouterStage